name: My First Pipeline            # any name

on:
  push:                            # when start
    branches:                      # konsi branch
      - main
      - develop
      - staging
#on:
#  schedule:
#    - cron: '0 0 * * *'          # every day at 12:00 AM
      
jobs:                              # what work
  first-job: 
    runs-on: ubuntu-latest         # where execute
    env:
      APP_NAME: EduPak
      VERSION: 1.0.0        
    steps:                         # every step
      - name: print your name
        run: echo "Warisha Ahmed"  # execute this command on terminal 
      - run: echo "App $APP_NAME"
      - run: echo "Version $VERSION"    
  
  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - run: echo "Both jobs workinkg"
  
  third-job:
    runs-on: ubuntu-latest
    needs: [first-job, second-job]
    steps:
      - run: echo "All jobs working"

      - name: today Date
        run: |
          echo "print username"
          echo "print disk space"
          uname
          df -h

      - name: file list
        run: ls
